venv) achhab16@LAMU0N62HHYPH2V backend % deepeval test run test_example.py
FRunning teardown with pytest sessionfinish...

=================================================================== FAILURES ===================================================================
___________________________________________________________ test_chatbot_correctness ___________________________________________________________

    @pytest.mark.deepeval
    def test_chatbot_correctness():
       """
       Test case to check if the chatbot correctly answers health insurance queries.
       """
       user_question = "What is deductible for plan code BXAL for tier 2 COC Series 2023?"
       expected_output = "Individual Ded is $4,000 and Family Ded is $8,000."
       # Call Azure OpenAI to get actual output
       actual_output = call_azure_openai(user_question)
>      assert actual_output is not None, "Azure OpenAI API call failed."
E      AssertionError: Azure OpenAI API call failed.
E      assert None is not None

test_example.py:49: AssertionError
-------------------------------------------------------------- Captured log call ---------------------------------------------------------------
ERROR    root:test_example.py:37 OpenAI API Error: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
============================================================= slowest 10 durations =============================================================

(3 durations < 0.005s hidden.  Use -vv to show these durations.)
=========================================================== short test summary info ============================================================
FAILED test_example.py::test_chatbot_correctness - AssertionError: Azure OpenAI API call failed.
1 failed, 3 warnings in 0.10s
No test cases found, please try again.
