venv) achhab16@LAMU0N62HHYPH2V backend % deepeval test run test_example.py
/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/__init__.py:54: UserWarning: You are using deepeval version 2.5.1, however version 2.5.2 is available. You should consider upgrading via the "pip install --upgrade deepeval" command.
  warnings.warn(
Running teardown with pytest sessionfinish...

==================================================================== ERRORS ====================================================================
_______________________________________________________ ERROR collecting test_example.py _______________________________________________________
test_example.py:20: in <module>
    azure_openai_model = GPTModel(
venv/lib/python3.13/site-packages/deepeval/models/gpt_model.py:154: in __init__
    raise ValueError(
E   ValueError: Invalid model. Available GPT models: gpt-3.5-turbo, gpt-3.5-turbo-0125, gpt-3.5-turbo-1106, gpt-4-0125-preview, gpt-4-1106-preview, gpt-4-turbo, gpt-4-turbo-2024-04-09, gpt-4-turbo-preview, gpt-4o, gpt-4o-2024-05-13, gpt-4o-2024-08-06, gpt-4o-2024-11-20, gpt-4o-mini, gpt-4o-mini-2024-07-18, gpt-4-32k, gpt-4-32k-0613, o1, o1-preview, o1-2024-12-17, o3-mini, o3-mini-2025-01-31
=========================================================== short test summary info ============================================================
ERROR test_example.py - ValueError: Invalid model. Available GPT models: gpt-3.5-turbo, gpt-3.5-turbo-0125, gpt-3.5-turbo-1106, gpt-4-0125-preview, gpt-4-1106-prev...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
3 warnings, 1 error in 0.13s
No test cases found, please try again.
